/// <summary>
/// Code generated 14/09/2020 9:34:15 by EFClassGenerator version 1.0.0.0
/// Template last modified 14/08/2020
/// </summary>

export interface XRSKDesgloseContr {
  DCP_CPT_TRI_MN_Cb1: number,
  DCP_CPT_TRI_MN_Cb2: number,
  DCP_ImpTri_CPT_MN: number,
  DCP_ImpTri_PAR_CPT: number,
  DCP_ImpTri_PAR_MN: number,
  DCP_Par_TRI_CPT_Cb1: number,
  DCP_Par_TRI_CPT_Cb2: number,
  DCP_Par_TRI_MN_Cb1: number,
  DCP_Par_TRI_MN_Cb2: number,
  DCPAgrupacionContrapartidaCPT: string,
  DCPBaseImponible: number,
  DCPCambioDivCptMn: number,
  DCPCambioDivisaCpt: number,
  DCPCodCPT: string,
  DCPComisCambioCPT: boolean,
  DCPComisionCPT: boolean,
  DCPConceptoFicticioCPT: boolean,
  DCPContrapartCPT: boolean,
  DCPCtaIVACPT: string,
  DCPCuentaContableCPT: string,
  DCPDescripcionCPT: string,
  DCPDiferenciasCPT: boolean,
  DCPDivisa: string,
  DCPDivisaCpt: string,
  DCPGrupo: string,
  DCPGtosBancCPT: boolean,
  DCPImporte: number,
  DCPImporteCpt: number,
  DCPImporteCptMn: number,
  DCPInteresesCPT: boolean,
  DCPIVACPT: boolean,
  DCPLibre1CPT: boolean,
  DCPLibre2CPT: boolean,
  DCPLibre3CPT: boolean,
  DCPLibre4CPT: boolean,
  DCPLibre5CPT: boolean,
  DCPLibre6CPT: boolean,
  DCPLibre7CPT: boolean,
  DCPLibre8CPT: boolean,
  DCPMonedaCPT: boolean,
  DCPPorcentajeIVACPT: number,
  DCPRefAnalitica1: string,
  DCPRefAnalitica2: string,
  DCPRefAnalitica3: string,
  DCPRefAnalitica4: string,
  DCPRefAnalitica5: string,
  DCPRefAnalitica6: string,
  DCPRefCont: string,
  DCPSignoCPT: number,
  DCPCodCIA: string,
  DCPValorOrganizativo: string,
  DCPRefXrisk: number,
  DCPContador: number,
  importe: number,
  importeOperacion: number,
  importeMonGrupo: number,
  analitica: string,
  refanalitica: string;
}

export class XRSKDesglose {
  DCP_CPT_TRI_MN_Cb1: number;
  DCP_CPT_TRI_MN_Cb2: number;
  DCP_ImpTri_CPT_MN: number;
  DCP_ImpTri_PAR_CPT: number;
  DCP_ImpTri_PAR_MN: number;
  DCP_Par_TRI_CPT_Cb1: number;
  DCP_Par_TRI_CPT_Cb2: number;
  DCP_Par_TRI_MN_Cb1: number;
  DCP_Par_TRI_MN_Cb2: number;
  DCPAgrupacionContrapartidaCPT: string;
  DCPBaseImponible: number;
  DCPCambioDivCptMn: number;
  DCPCambioDivisaCpt: number;
  DCPCodCPT: string;
  DCPComisCambioCPT: boolean;
  DCPComisionCPT: boolean;
  DCPConceptoFicticioCPT: boolean;
  DCPContrapartCPT: boolean;
  DCPCtaIVACPT: string;
  DCPCuentaContableCPT: string;
  DCPDescripcionCPT: string;
  DCPDiferenciasCPT: boolean;
  DCPDivisa: string;
  DCPDivisaCpt: string;
  DCPGrupo: string;
  DCPGtosBancCPT: boolean;
  DCPImporte: number;
  DCPImporteCpt: number;
  DCPImporteCptMn: number;
  DCPInteresesCPT: boolean;
  DCPIVACPT: boolean;
  DCPLibre1CPT: boolean;
  DCPLibre2CPT: boolean;
  DCPLibre3CPT: boolean;
  DCPLibre4CPT: boolean;
  DCPLibre5CPT: boolean;
  DCPLibre6CPT: boolean;
  DCPLibre7CPT: boolean;
  DCPLibre8CPT: boolean;
  DCPMonedaCPT: boolean;
  DCPPorcentajeIVACPT: number;
  DCPRefAnalitica1: string;
  DCPRefAnalitica2: string;
  DCPRefAnalitica3: string;
  DCPRefAnalitica4: string;
  DCPRefAnalitica5: string;
  DCPRefAnalitica6: string;
  DCPRefCont: string;
  DCPSignoCPT: number;
  DCPCodCIA: string;
  DCPValorOrganizativo: string;
  DCPRefXrisk: number;
  DCPContador: number;
  refanalitica: string;
}
